version: '3.8'

services:
  php:
    build:
      context: .
    container_name: php-container
    volumes:
      - ./src:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "8080:80"
    environment:
      XDEBUG_MODE: debug
